[package]
name = "vault"
version = "0.1.0"

[dependencies]
starknet = ">=2.5.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", branch = "main" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
