[package]
name = "vault"
version = "0.1.0"

[dependencies]
starknet = "=2.6.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", branch = "main" }
baz = { git = "https://github.com/LucasLvy/baz"}

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
